only_reportables: true

preprocessing:
  extract_prefix: true # split lemmas by prefix and suffix
  morph_code_only: false
  flat_suff_person: true  # remove person-form indicator, or not
  ng_min: 1  # min_ngram
  ng_max: 1  # max_ngram (must be larger than ng_min)
  pad: true # add <start>/<end> symbols at the begining/ending of verses
  to_remove: # morpholical pad_ledcodes to remove (Np = proper name, Ng = gentilic noun),
             # see https://hb.openscriptures.org/parsing/HebrewMorphologyCodes.html
    - "FFF"  # that's a placeholder
    #- Np     # noun proper
    #- Ng     # noun gentile
    #- Ac     # cardinal number
  to_replace: # morpholical pad_ledcodes to replace by a symbol
    - "FFF"
    #- Ac # cardinal number
    - Ng # noun gentilic
    - Np # name proper
    #- Pp # Proposition personal
    #- Rd # preposition definite article
    # - Nc # noun comon
    #- Vq # verb

vocab:
  no_tokens: 3000  # most frequent tokens
  by_author: true  # most frequent by each author of the known_authors list
  authors:
    - Dtr
    - DtrH
    - P

model:
  feat_reduction_method: "none" # options are: div_persuit, one_vs_many, none
  gamma: .35  # HC parameter (lower fraction of P-values to consider)
  stbl: true  # type of HC
  #min_cnt: 1
  measures:   # list of discrepancy measures available
    - 'HC'
    - 'Fisher' # Fisher's combination test
    - 'majority'
    #- 'chisq' # chisquared test
  n_fold: 2 # number of splits in CV mode

known_authors:
  - Dtr
  - DtrH
  - P

unknown_authors:
  - Ark1
  - Ark2
  - Late_Abraham
  - Gibea
  - Early_Jacob
  - Chr2
  - Chr1
  - Chr
  - Esth
  - Prov
  - Lev26
  - Deut4

all_authors:
  - Dtr
  - DtrH
  - P
  - Ark1
  - Ark2
  - Late_Abraham
  - Gibea
  - Early_Jacob
  - Chr2
  - Chr1
  - Chr
  - Esth
  - Prov
  - Lev26
  - Deut4

report:
  log_scale: true
  value: 'HC'
  #value: 'majority'
  #value: 'Fisher'
  #value: 'chisq'
  fig_path: 'data/08_reporting/Figs'
  anova: False
  min_length_to_report: 100 # only include texts of at least min_length words
  sig_level: .05            # significance level for rank-based testing
  known_authors:
  - Dtr
  - DtrH
  - P
  unknown_authors:
  - Ark1
  - Ark2
  - Late_Abraham
  - Gibea
  - Early_Jacob
  - Chr2
  - Chr1
  - Chr
  - Esth
  - Prov
  - Lev26
  - Deut4

bootstrapping:
  nBS: 20
  value: 'HC'
  reduce_feature: None

sim_full: # Make sure that n is larger than max_no_docs_per_corpus.
          # These parameters are
          # required to simulate a different null distribution, e.g.,
          # by sampling text chunks in future versions.
  n: 200
  min_length_to_consider: 100
  sampling_method: "doc_id"
  random: false
  sample_w_replacements: true  # only relevant if random=true
  sample_contiguous: true      # only relevant if random=true

features:
  fig_path: 'data/08_reporting/Figs'
  out_path: 'data/08_reporting/'
  num_features_to_plot: 30
  known_authors:
    - Dtr
    - DtrH
    - P
  specific_chapters:
    - "Ark1|Ark1"
    - "Ark2|Ark2"
    - "Chr1|Chr1"
    - "Chr2|Chr2"
    - "Early_Jacob|Early_Jacob"
    - "Esth|Esth"
    - "Gibea|Gibea"
    - "Late_Abraham|Late_Abraham"
    - "Deut4|Deut.4"
    - "Lev26|Lev26"
    - "Prov|Prov"
    - "DtrH|Josh.1"
    - "DtrH|Judg.2"
    - "P|Gen.17"
    - "P|Exod.6"
    - "Dtr|Deut.8"
    - "Dtr|Deut.28"
    - "DtrH|Josh.23"
    - "Dtr|Deut.6"
    - "DtrH|Deut.26"
    - "DtrH|Deut.11"
    - "Chr|chapter0"

chunk_len_params:
  sampling_method: "verse"
  contiguous_chunk: "false"
  nMonte: 500
  chunk_lengths:
    - 5
    - 10
    - 30
    - 50
    - 75
    - 100
    - 125
    - 150
    - 175
    - 200
    - 250
  chunk_lengths1:
    - 50
    - 100
    - 200
    - 300
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
    - 1300
    - 1400
    - 1500
    - 1600
    - 1800
    - 2000
    - 2250
    - 2500

