# This configuration resulted in 92% accuracy

preprocessing:
  extract_prefix: true # split lemmas by prefix and suffix
  morph_code_only: false
  flat_suff_person: true  # remove person-form indicator, or not
  ng_min: 1  # min_ngram
  ng_max: 1  # max_ngram (must be larger than ng_min)
  pad: false # add <start>/<end> symbols at the begining/ending of verses
  to_remove: # morpholical pad_ledcodes to remove (Np = proper name, Ng = gentilic noun),
             # see https://hb.openscriptures.org/parsing/HebrewMorphologyCodes.html
    - "FFF"  # that's a placeholder
    #- Np     # noun proper
    #- Ng     # noun gentile
    #- Ac     # cardinal number
  to_replace: # morpholical pad_ledcodes to replace by a symbol
    - "FFF"
    #- Ac # cardinal number
    - Ng # noun gentilic
    - Np # name proper
    #- Pp # Proposition personal
    #- Rd # preposition definite article
    # - Nc # noun comon
    #- Vq # verb

vocab:
  no_tokens: 3000  # most frequent tokens
  by_author: true  # most frequent by each author of the known_authors list

model:
  feat_reduction_method: "none" # options are: div_persuit, one_vs_many, none
  gamma: .25  # HC parameter (lower fruction of P-values to consider)
  stbl: true  # type of HC
  #min_cnt: 1
  measures:   # list of discrepancy measures available
    - 'HC'
    #- 'Fisher' # Fisher's combination test
    #- 'chisq' # chisquared test

known_authors:
  - Dtr
  - DtrH
  - P

unknown_authors:
  - Ark1
  - Ark2
  - Late_Abraham
  - Gibea
  - Early_Jacob
  - Chr2
  - Chr1
  - Esth
  - Prov
  - Lev26

all_authors:
  - Dtr
  - DtrH
  - P
  - Ark1
  - Ark2
  - Late_Abraham
  - Gibea
  - Early_Jacob
  - Chr2
  - Chr1
  - Esth
  - Prov
  - Lev26
  #- Deut4

report:
  value: 'HC'
  #value: 'Fisher'
  #value: 'chisq'
  fig_path: 'data/08_reporting/Figs'
  min_length_to_report: 100 # only include texts of at least min_length words
  sig_level: .05            # significance level for rank-based testing
  known_authors:
  - Dtr
  - DtrH
  - P
  unknown_authors:
  - Ark1
  - Ark2
  - Late_Abraham
  - Gibea
  - Early_Jacob
  - Chr2
  - Chr1
  - Esth
  - Prov
  - Lev26
  #- Deut4

features:
  fig_path: 'data/08_reporting/Figs'
  num_features_to_plot: 30
  known_authors:
    - Dtr
    - DtrH
    - P
  specific_chapters:
    - "DtrH|Josh.1"
    - "DtrH|Judg.2"
    - "P|Gen.17"
    - "P|Exod.6"


bootstrapping:
  nBS: 100
  value: 'HC'
  reduce_feature: None

sim_full: # Make sure that n is larger than max_no_docs_per_corpus.
          # These parameters are
          # required to simulate a different null distribution, e.g.,
          # by sampling text chunks
  n: 200
  min_length_to_consider: 100
  sampling_method: "doc_id"
  random: false
  sample_w_replacements: true  # not used unless random=true
  sample_contiguous: true  # not used unless random=true


chunk_len_params:
  sampling_method: "lemma"
  contiguous_chunk: "true"
  nMonte: 500
  chunk_lengths:
    - 200
    - 300
    - 400
    - 500
    - 600
    - 700
    - 800
    - 900
    - 1000
    - 1100
    - 1200
    - 1300
    - 1400
    - 1500
    - 1600
    - 1700
    - 1800
    - 1900
    - 2000
